flowchart TB
  subgraph n_src_knowledge_store["src-knowledge-store"]
    n_src_knowledge_store_KnowledgeStore_js["store/KnowledgeStore.js"]
  end
  n_src_knowledge_store --> n_src_knowledge_model["src-knowledge-model"]
