flowchart TB
  subgraph n_src_static_analysis_ast["src-static-analysis-ast"]
    n_src_static_analysis_ast_extractors_js["ast/extractors.js"]
    n_src_static_analysis_ast_parseFile_js["ast/parseFile.js"]
  end
