import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createCursorPathContext } from './pathRewrite.js';
import { requirementIntakeRuleSection } from './requirementAnalysisRules.js';
import { taskCompletionImpactRuleSection } from './completionImpactRules.js';
import { tapdSubmitRuleSection } from './tapdSubmitRules.js';
import { fileLicenseRuleSection } from './fileLicenseRules.js';

/**
 * Hermes adapter for AAFE.
 *
 * Hermes Agent discovers project context via `AGENTS.md` at the workspace root
 * (or install root for flat installs). The file is auto-injected into the system
 * prompt, making it the primary bridge for AAFE Rules/Skills reachability.
 *
 * This adapter generates:
 *   - AGENTS.md — always-on rules + skill router + runtime pipeline pointer
 *   - .hermes/skills/aafe-runtime/SKILL.md — Hermes-native skill entry
 *
 * For layered (monorepo) installs, AGENTS.md is written at the workspace root
 * with module-relative paths. For flat installs, it lives at the install root.
 */

export async function writeLayeredHermesAdapters({
  workspaceRoot,
  moduleName,
  moduleRelativePath,
  options = {}
}) {
  const ctx = createCursorPathContext(moduleName, moduleRelativePath);
  const agentsMd = buildHermesAgentsMd(ctx, true);
  const skill = buildHermesSkill(ctx, true);

  await writeIfAllowed(path.join(workspaceRoot, 'AGENTS.md'), agentsMd, { ...options, append: true });
  await writeIfAllowed(
    path.join(workspaceRoot, '.hermes', 'skills', 'aafe-runtime', 'SKILL.md'),
    skill,
    options
  );
  return { agentsMdPath: path.join(workspaceRoot, 'AGENTS.md'), skillPath: path.join(workspaceRoot, '.hermes', 'skills', 'aafe-runtime', 'SKILL.md') };
}

export async function writeFlatHermesAdapters(root, options = {}) {
  const ctx = createCursorPathContext('root', '.');
  const agentsMd = buildHermesAgentsMd(ctx, false);
  const skill = buildHermesSkill(ctx, false);

  await writeIfAllowed(path.join(root, 'AGENTS.md'), agentsMd, { ...options, append: true });
  await writeIfAllowed(
    path.join(root, '.hermes', 'skills', 'aafe-runtime', 'SKILL.md'),
    skill,
    options
  );
  return { agentsMdPath: path.join(root, 'AGENTS.md'), skillPath: path.join(root, '.hermes', 'skills', 'aafe-runtime', 'SKILL.md') };
}

/**
 * Build the AGENTS.md content for Hermes.
 *
 * Hermes auto-injects AGENTS.md into the system prompt, so this file must
 * contain the always-on AAFE rules (requirement intake, task completion,
 * TAPD submit, file license) plus the skill router and runtime pipeline
 * pointer — all using paths relative to the workspace root.
 */
function buildHermesAgentsMd(ctx, layered) {
  const sections = [
    '# AAFE Architecture Runtime',
    '',
    `> Generated by \`@aafe/agent-runtime\` for ${layered ? `module \`${ctx.moduleName}\` (\`${ctx.moduleRelativePath}\`)` : 'this project'}.`,
    '> Hermes auto-injects this file into the system prompt. Do not edit manually.',
    '',
    '## Requirement intake (before code)',
    '',
    requirementIntakeRuleSection(ctx).trim(),
    '',
    '## Task completion impact and test (conditional)',
    '',
    taskCompletionImpactRuleSection(ctx).trim(),
    '',
    '## TAPD submit backfill',
    '',
    tapdSubmitRuleSection(ctx).trim(),
    '',
    '## File license',
    '',
    fileLicenseRuleSection(ctx).trim(),
    '',
    '## AAFE Skill Router',
    '',
    `For every task${layered ? ` in module \`${ctx.moduleRelativePath}\`` : ''}, read \`${ctx.agentPrefix}/skill-index.md\` first, then \`${ctx.agentPrefix}/project.md\` if present, and only the matching \`${ctx.agentPrefix}/project-skills/<domain>/SKILL.md\` on demand.`,
    `Do not copy project knowledge into \`.hermes/\`; the single source of truth is \`${ctx.agentPrefix}/\`.`,
    '',
    '## Runtime Pipeline',
    '',
    `For non-trivial frontend work, load \`${ctx.agentPrefix}/runtime/engine.md\`, classify with \`${ctx.agentPrefix}/runtime/router.yaml\`, follow the selected \`${ctx.agentPrefix}/pipelines/*.yaml\`, and enforce \`${ctx.agentPrefix}/runtime/gates.yaml\`.`,
    ''
  ];

  return sections.filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
}

/**
 * Build the Hermes-native skill file.
 * Hermes discovers skills from `.hermes/skills/<name>/SKILL.md`.
 */
function buildHermesSkill(ctx, layered) {
  const moduleHint = layered
    ? `module \`${ctx.moduleName}\` (\`${ctx.moduleRelativePath}\`)`
    : 'this project';
  return [
    '---',
    'name: aafe-runtime',
    `description: Use the AAFE project runtime for architecture-aware frontend work in ${moduleHint}. Load this skill for ANY task that touches this module — components, routes, Vue/React/TS, requirement intake, impact analysis, self-test, or TAPD backfill. It routes to the module knowledge base at ${ctx.agentPrefix}.`,
    '---',
    '',
    `# AAFE Runtime (Hermes / ${ctx.moduleName})`,
    '',
    `模块：\`${ctx.moduleName}\`，物理路径：\`${ctx.moduleRelativePath}\`，知识库根：\`${ctx.agentPrefix}\`。`,
    '',
    '## 加载顺序',
    '',
    `1. Read \`${ctx.agentPrefix}/skill-index.md\` first —— 技能索引，决定要加载哪个 domain。`,
    `2. Read \`${ctx.agentPrefix}/project.md\` when present —— 项目地图与使用约束。`,
    `3. Read \`${ctx.agentPrefix}/runtime/engine.md\`、\`runtime/router.yaml\`、\`runtime/gates.yaml\` —— 执行引擎、任务分类、门禁。`,
    `4. 按需加载匹配的 \`${ctx.agentPrefix}/project-skills/<domain>/SKILL.md\`，不要一次性全量加载。`,
    '',
    '## 边界',
    '',
    `- 优先在 \`${ctx.moduleRelativePath}\` 范围内改动；跨模块需先确认。`,
    `- 运行时知识只存放在 \`${ctx.agentPrefix}/\`，不要写入 \`.hermes/\`。`,
    `- 完整的常驻约束见项目根目录 \`AGENTS.md\`。`,
    ''
  ].join('\n');
}

async function writeIfAllowed(filePath, content, options) {
  if (options.dryRun) return;
  await mkdir(path.dirname(filePath), { recursive: true });
  const fileExists = await exists(filePath);

  if (options.append && fileExists) {
    const existing = await safeRead(filePath);
    // Avoid duplicate appends: check if content already present.
    const marker = '> Generated by `@aafe/agent-runtime`';
    if (existing.includes(marker)) {
      // Replace existing AAFE section instead of duplicating.
      const updated = replaceAafeSection(existing, content);
      if (updated !== existing) {
        await writeFile(filePath, updated);
      }
      return;
    }
    // Append with separator
    const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
    await writeFile(filePath, existing + separator + content);
    return;
  }

  if (!options.force && fileExists) return;
  if (fileExists) {
    const previous = await safeRead(filePath);
    if (previous === content) return;
  }
  await writeFile(filePath, content);
}

/**
 * Replace an existing AAFE-generated section in AGENTS.md.
 * Looks for the marker line and replaces everything from there to EOF
 * (or to the next non-AAFE section marker).
 */
function replaceAafeSection(existing, newContent) {
  const marker = '# AAFE Architecture Runtime';
  const idx = existing.indexOf(marker);
  if (idx === -1) return existing;
  return existing.slice(0, idx) + newContent;
}

async function exists(filePath) {
  try {
    await stat(filePath);
    return true;
  } catch {
    return false;
  }
}

async function safeRead(filePath) {
  try {
    return await readFile(filePath, 'utf8');
  } catch {
    return '';
  }
}
