/*
 * Tencent is pleased to support the open source community by making
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) available.
 * Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) is licensed under the MIT License.
 * License for 蓝鲸智云PaaS平台 (BlueKing PaaS):
 * ---------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { combineEntryUrl, parseTestPageUrl, normalizeUrlRole } from './config.js';
import { normalizeEntry } from './yaml.js';

/**
 * Compile an AITest-compatible YAML case into a Playwright spec string.
 * Specs are derived artifacts under .aafe/e2e/specs/ — YAML remains the source of truth.
 */
export function compileCaseToSpec(testCase, { baseUrlEnv = 'AAFE_E2E_BASE_URL', baseUrl = null, urlRole = null } = {}) {
  const title = testCase.title || testCase.id;
  const entry = normalizeEntry(testCase.entry?.path ?? testCase.entry);
  const role = normalizeUrlRole(urlRole);
  const steps = (testCase.steps ?? []).map((step) => renderStep(step, entry, { baseUrl, urlRole: role })).join('\n');
  const assertions = (testCase.assertions ?? []).map((assertion) => renderAssertion(assertion)).join('\n');

  return `/**
 * Generated by AAFE from YAML case ${testCase.id}. Do not edit; regenerate from tests/ui-ai/cases/.
 */
import { expect, test } from '@playwright/test';

test(${JSON.stringify(title)}, async ({ page }) => {
  const consoleErrors = [];
  const httpErrors = [];
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });
  page.on('response', (response) => {
    if (response.status() >= 400) httpErrors.push(response.status() + ' ' + response.url());
  });
${steps}
${assertions}
});

function entryUrl() {
  const base = String(process.env[${JSON.stringify(baseUrlEnv)}] ?? '') || ${JSON.stringify(baseUrl ?? '')};
  const entryPath = ${JSON.stringify(entry)};
  if (/^https?:\\/\\//i.test(entryPath)) return entryPath;
  if (!base) return entryPath;
  return joinPageUrl(base, entryPath, ${JSON.stringify(role)});
}

function joinPageUrl(base, entryPath, urlRole) {
  let url;
  try { url = new URL(base); } catch {
    return String(base).replace(/\\/+$/, '') + (entryPath.startsWith('/') ? entryPath : '/' + entryPath);
  }
  const hashBody = url.hash.startsWith('#') ? url.hash.slice(1) : '';
  const hashMode = url.hash === '#' || hashBody.startsWith('/');
  const q = hashBody.indexOf('?');
  const hashPath = (q >= 0 ? hashBody.slice(0, q) : hashBody) || '';
  const hashQuery = q >= 0 ? hashBody.slice(q + 1) : '';
  const query = urlRole === 'origin' ? '' : (hashQuery || url.search.replace(/^\\?/, ''));
  const appBase = (url.origin + url.pathname).replace(/\\/+$/, '') || url.origin;
  const suffix = entryPath.startsWith('/') ? entryPath : '/' + entryPath;
  const normalizedHashPath = hashPath && !hashPath.startsWith('/') ? '/' + hashPath : hashPath;
  const pagePath = hashMode ? normalizedHashPath : url.pathname;
  if (urlRole === 'target' && pagePath && pagePath.replace(/\\/+$/, '') === suffix.replace(/\\/+$/, '')) return base;
  const qs = query ? '?' + query : '';
  if (hashMode) return appBase + '/#' + suffix + qs;
  return appBase + suffix + qs;
}
`;
}

export async function writeCompiledSpecs(specsDir, cases, options = {}) {
  await mkdir(specsDir, { recursive: true });
  const written = [];
  for (const testCase of cases) {
    const file = path.join(specsDir, `${testCase.id}.spec.js`);
    await writeFile(file, compileCaseToSpec(testCase, options), 'utf8');
    written.push(file);
  }
  return written;
}

export function renderPlaywrightConfig({ specsDir, reportDir, baseUrl = null, storageState = null }) {
  const parsed = parseTestPageUrl(baseUrl);
  const config = {
    testDir: specsDir,
    testMatch: '*.spec.js',
    outputDir: path.join(reportDir, 'artifacts'),
    reporter: [
      ['json', { outputFile: path.join(reportDir, 'playwright.json') }]
    ],
    use: {
      baseURL: parsed?.appBase || baseUrl || undefined,
      storageState: storageState || undefined,
      screenshot: 'only-on-failure',
      trace: 'retain-on-failure',
      video: 'retain-on-failure'
    }
  };
  return `// Generated by AAFE. All Playwright output stays under this report directory.
export default ${JSON.stringify(config, null, 2)};
`;
}

function renderStep(step, entry, { baseUrl = null, urlRole = null } = {}) {
  const action = step.action;
  if (action === 'navigate') {
    if (step.target === 'entry' || !step.target) {
      return '  await page.goto(entryUrl());';
    }
    const target = /^https?:\/\//i.test(step.target)
      ? step.target
      : combineEntryUrl(baseUrl || '', step.target, { urlRole });
    return `  await page.goto(${JSON.stringify(target)});`;
  }
  if (action === 'wait') {
    if (step.target === 'visible' || step.target === 'hidden') {
      return `  await page.locator(${JSON.stringify(step.value || 'body')}).waitFor({ state: ${JSON.stringify(step.target)} });`;
    }
    const state = ['load', 'domcontentloaded', 'networkidle'].includes(step.target) ? step.target : 'load';
    return `  await page.waitForLoadState(${JSON.stringify(state)});`;
  }
  if (action === 'tap') {
    return `  await page.click(${JSON.stringify(step.target)});`;
  }
  if (action === 'input') {
    return `  await page.fill(${JSON.stringify(step.target)}, ${JSON.stringify(step.value ?? '')});`;
  }
  if (action === 'select') {
    return `  await page.selectOption(${JSON.stringify(step.target)}, ${JSON.stringify(step.value ?? '')});`;
  }
  return `  // skipped unsupported step ${action}`;
}

function renderAssertion(assertion) {
  const check = assertion.check;
  if (check === 'console-no-errors') {
    return '  expect(consoleErrors, "console-no-errors").toEqual([]);';
  }
  if (check === 'network-no-http-errors') {
    return '  expect(httpErrors, "network-no-http-errors").toEqual([]);';
  }
  if (check === 'dom-exists') {
    return `  await expect(page.locator(${JSON.stringify(assertion.selector || 'body')}).first()).toBeVisible();`;
  }
  return `  // skipped unsupported assertion ${check}`;
}
