/*
 * Tencent is pleased to support the open source community by making
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) available.
 * Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) is licensed under the MIT License.
 * License for 蓝鲸智云PaaS平台 (BlueKing PaaS):
 * ---------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const SMOKE_ID = /^SMOKE-(\d{3})$/;
const CASE_ID = /^[A-Z][A-Z0-9_-]*-[0-9]{3}$/;
const FORBIDDEN = /\b(REPLACE_\w+|TODO|PLACEHOLDER|待替换)\b/;

export function normalizeEntry(entryPath) {
  const value = String(entryPath ?? '').trim();
  if (!value) return '';
  if (/^https?:\/\//i.test(value)) return value;
  return value.startsWith('/') ? value : `/${value}`;
}

export function isRealRoute(entryPath) {
  const raw = String(entryPath ?? '').trim();
  if (!raw || raw.includes('${') || raw.includes('...')) return false;
  if (/^https?:\/\//i.test(raw)) return true;
  if (!raw.startsWith('/')) return false;
  const pathOnly = raw.split(/[?#]/)[0];
  if (/\.[a-zA-Z][a-zA-Z0-9]{0,7}$/.test(pathOnly)) return false;
  return pathOnly.startsWith('/');
}

export function nextIds(existingIds, prefix, count) {
  const pattern = new RegExp(`^${prefix}-(\\d{3})$`);
  let max = 0;
  for (const id of existingIds) {
    const match = String(id).match(pattern);
    if (match) max = Math.max(max, Number.parseInt(match[1], 10));
  }
  return Array.from({ length: count }, (_, index) => `${prefix}-${String(max + index + 1).padStart(3, '0')}`);
}

export function renderSmokeCase(id, entry, { sourcePath = null, sourceKind = 'quality-gate', sourceRef = 'inventory-smoke' } = {}) {
  const pathJson = JSON.stringify(normalizeEntry(entry));
  const sourceBlock = sourcePath
    ? `  - kind: authoritative-doc\n    path: ${sourcePath}\n`
    : '';
  return `# Generated by AAFE e2e from analyze coverage. Accessibility smoke, not business acceptance.
id: ${id}
title: 冒烟：打开 ${normalizeEntry(entry)}
priority: P0
engine: playwright
sources:
  - kind: ${sourceKind}
    ref: ${sourceRef}
    section: full-suite
${sourceBlock}entry:
  path: ${pathJson}
preconditions:
  - type: environment
    name: AAFE_E2E_BASE_URL
    description: 被测服务可访问时执行冒烟
    required: false
steps:
  - action: navigate
    target: entry
  - action: wait
    target: load
assertions:
  - id: assert-console
    check: console-no-errors
    expect: 无控制台错误
    policy: primary
  - id: assert-network
    check: network-no-http-errors
    expect: 无网络 HTTP 错误
    policy: primary
`;
}

export function renderFeatureCase(id, { title, entry, featureId, sourcePath = null }) {
  const pathJson = JSON.stringify(normalizeEntry(entry));
  const sourceBlock = sourcePath
    ? `  - kind: authoritative-doc\n    path: ${sourcePath}\n`
    : '';
  return `# Generated by AAFE e2e from analyze feature ${featureId ?? ''}.
id: ${id}
title: ${title}
priority: P1
engine: playwright
sources:
  - kind: quality-gate
    ref: analyze-feature
    section: feature-coverage
${sourceBlock}entry:
  path: ${pathJson}
preconditions:
  - type: environment
    name: AAFE_E2E_BASE_URL
    description: 被测服务可访问时执行功能覆盖
    required: false
steps:
  - action: navigate
    target: entry
  - action: wait
    target: load
assertions:
  - id: assert-console
    check: console-no-errors
    expect: 无控制台错误
    policy: primary
  - id: assert-network
    check: network-no-http-errors
    expect: 无网络 HTTP 错误
    policy: primary
`;
}

export function assertNoPlaceholders(caseText) {
  const executable = String(caseText ?? '')
    .split('\n')
    .filter((line) => !/^\s*(#|title:|description:)/.test(line))
    .join('\n');
  if (FORBIDDEN.test(executable)) {
    throw new Error('e2e case contains placeholder in an executable field');
  }
}

export function parseCaseYaml(text) {
  const raw = String(text ?? '');
  const id = matchLine(raw, /^id:\s*(.+)$/m);
  const title = unquote(matchLine(raw, /^title:\s*(.+)$/m));
  const priority = matchLine(raw, /^priority:\s*(.+)$/m) || 'P0';
  const engine = matchLine(raw, /^engine:\s*(.+)$/m) || 'playwright';
  const entry = unquote(raw.match(/entry:\s*\n\s*path:\s*(.+)/)?.[1] ?? '');
  const steps = parseSteps(raw);
  const assertions = parseAssertions(raw);
  return {
    id,
    title,
    priority,
    engine,
    entry: { path: normalizeEntry(entry) },
    steps,
    assertions,
    sources: [{ kind: 'quality-gate', ref: 'parsed' }],
    preconditions: [{ type: 'environment', name: 'AAFE_E2E_BASE_URL', required: false }]
  };
}

export async function listCases(casesDir) {
  if (!existsSync(casesDir)) return [];
  const names = await readdir(casesDir);
  const cases = [];
  for (const name of names) {
    if (!name.endsWith('.yaml') && !name.endsWith('.yml')) continue;
    const file = path.join(casesDir, name);
    try {
      const loaded = parseCaseYaml(await readFile(file, 'utf8'));
      if (loaded.id) cases.push({ ...loaded, file });
    } catch {
      cases.push({ id: path.basename(name, path.extname(name)), file });
    }
  }
  return cases;
}

export async function existingEntrySet(casesDir) {
  const entries = new Set();
  for (const item of await listCases(casesDir)) {
    const entry = normalizeEntry(item.entry?.path);
    if (entry) entries.add(entry);
  }
  return entries;
}

export async function writeCases(casesDir, files) {
  await mkdir(casesDir, { recursive: true });
  const written = [];
  for (const file of files) {
    assertNoPlaceholders(file.content);
    const target = path.join(casesDir, file.name);
    if (existsSync(target)) continue;
    await writeFile(target, file.content, 'utf8');
    written.push({ id: file.id, file: target, entry: file.entry ?? null });
  }
  return written;
}

export function caseFileName(id) {
  if (!CASE_ID.test(id) && !SMOKE_ID.test(id)) {
    throw new Error(`invalid case id: ${id}`);
  }
  return `${id}.yaml`;
}

function matchLine(text, pattern) {
  return text.match(pattern)?.[1]?.trim() ?? '';
}

function unquote(value) {
  const trimmed = String(value ?? '').trim();
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    try {
      return JSON.parse(trimmed.startsWith("'") ? `"${trimmed.slice(1, -1)}"` : trimmed);
    } catch {
      return trimmed.slice(1, -1);
    }
  }
  return trimmed;
}

function parseSteps(raw) {
  const block = section(raw, 'steps:');
  const steps = [];
  let current = null;
  for (const line of block) {
    const action = line.match(/^\s*-\s*action:\s*(.+)$/);
    if (action) {
      if (current) steps.push(current);
      current = { action: action[1].trim() };
      continue;
    }
    const field = line.match(/^\s+(target|value):\s*(.+)$/);
    if (field && current) current[field[1]] = unquote(field[2]);
  }
  if (current) steps.push(current);
  return steps;
}

function parseAssertions(raw) {
  const block = section(raw, 'assertions:');
  const assertions = [];
  let current = null;
  for (const line of block) {
    const id = line.match(/^\s*-\s*id:\s*(.+)$/);
    if (id) {
      if (current) assertions.push(current);
      current = { id: id[1].trim() };
      continue;
    }
    const field = line.match(/^\s+(check|expect|policy|selector):\s*(.+)$/);
    if (field && current) current[field[1]] = unquote(field[2]);
  }
  if (current) assertions.push(current);
  return assertions;
}

function section(raw, header) {
  const lines = raw.split(/\r?\n/);
  const start = lines.findIndex((line) => line.startsWith(header));
  if (start < 0) return [];
  const out = [];
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (/^[a-zA-Z]/.test(line)) break;
    out.push(line);
  }
  return out;
}
