flowchart TD
  n_file_src_cli_bootstrap_js["src/cli/bootstrap.js"]
  n_file_src_templates_TemplateSystem_js["src/templates/TemplateSystem.js"]
  n_file_src_cli_bootstrap_js -->|IMPORTS| n_file_src_templates_TemplateSystem_js
