flowchart TD
  n_file_src_static_analysis_analyzers_graph_js["src/static-analysis/analyzers/graph.js"]
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_file_src_static_analysis_analyzers_graph_js -->|IMPORTS| n_file_src_static_analysis_routes_resolveRoutes_js
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_import_node_fs_promises["node:fs/promises"]
  n_file_src_static_analysis_routes_resolveRoutes_js -->|IMPORTS| n_import_node_fs_promises
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_import_node_path["node:path"]
  n_file_src_static_analysis_routes_resolveRoutes_js -->|IMPORTS| n_import_node_path
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_file_src_static_analysis_ast_parseFile_js["src/static-analysis/ast/parseFile.js"]
  n_file_src_static_analysis_routes_resolveRoutes_js -->|IMPORTS| n_file_src_static_analysis_ast_parseFile_js
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_file_src_static_analysis_ast_extractors_js["src/static-analysis/ast/extractors.js"]
  n_file_src_static_analysis_routes_resolveRoutes_js -->|IMPORTS| n_file_src_static_analysis_ast_extractors_js
  n_file_src_static_analysis_routes_resolveRoutes_js["src/static-analysis/routes/resolveRoutes.js"]
  n_file_src_static_analysis_resolve_ModuleResolver_["src/static-analysis/resolve/ModuleResolver.js"]
  n_file_src_static_analysis_routes_resolveRoutes_js -->|IMPORTS| n_file_src_static_analysis_resolve_ModuleResolver_
