/*
 * Tencent is pleased to support the open source community by making
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) available.
 * Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) is licensed under the MIT License.
 * License for 蓝鲸智云PaaS平台 (BlueKing PaaS):
 * ---------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/**
 * Render runnable test skeletons from a test plan.
 *
 * The generated files intentionally stop at the assertion boundary: steps and
 * expectations become comments and a failing `TODO` marker rather than invented
 * selectors. A skeleton that silently passes is worse than no test at all.
 */
export function generateTests(plan, { e2eRunner = null, unitRunner = null } = {}) {
  const files = [];
  const e2eScenarios = plan.scenarios.filter((scenario) => scenario.kind === 'e2e');
  const otherScenarios = plan.scenarios.filter((scenario) => scenario.kind !== 'e2e');

  if (e2eScenarios.length > 0) {
    const runner = e2eRunner ?? 'playwright';
    files.push({
      path: `tests/aafe/${fileStem(plan)}.e2e.spec.js`,
      runner,
      content: runner === 'cypress'
        ? renderCypress(e2eScenarios, plan)
        : renderPlaywright(e2eScenarios, plan)
    });
  }

  if (otherScenarios.length > 0) {
    const runner = unitRunner ?? 'vitest';
    files.push({
      path: `tests/aafe/${fileStem(plan)}.spec.js`,
      runner,
      content: renderUnit(otherScenarios, plan, runner)
    });
  }

  return files;
}

function renderPlaywright(scenarios, plan) {
  const body = scenarios.map((scenario) => `
test(${quote(scenario.title)}, async ({ page }) => {
${steps(scenario)}
${expectations(scenario)}
  test.fail(true, 'AAFE generated this skeleton; replace with real assertions.');
${navigation(scenario)}
});`).join('\n');

  return `${header(plan)}
import { expect, test } from '@playwright/test';

test.describe(${quote(describeTitle(plan))}, () => {
${indent(body)}
});
`;
}

function renderCypress(scenarios, plan) {
  const body = scenarios.map((scenario) => `
it(${quote(scenario.title)}, () => {
${steps(scenario)}
${expectations(scenario)}
  throw new Error('AAFE generated this skeleton; replace with real assertions.');
${cypressNavigation(scenario)}
});`).join('\n');

  return `${header(plan)}
describe(${quote(describeTitle(plan))}, () => {
${indent(body)}
});
`;
}

function renderUnit(scenarios, plan, runner) {
  const importLine = runner === 'jest'
    ? ''
    : "import { describe, expect, it } from 'vitest';\n";
  const body = scenarios.map((scenario) => `
it(${quote(scenario.title)}, () => {
${steps(scenario)}
${expectations(scenario)}
  expect.fail?.('AAFE generated this skeleton; replace with real assertions.')
    ?? expect(true, 'AAFE skeleton').toBe(false);
});`).join('\n');

  return `${header(plan)}
${importLine}
describe(${quote(describeTitle(plan))}, () => {
${indent(body)}
});
`;
}

function steps(scenario) {
  return scenario.steps.map((step) => `  // step: ${step}`).join('\n');
}

function expectations(scenario) {
  return scenario.expected.map((item) => `  // expect: ${item}`).join('\n');
}

function navigation(scenario) {
  return scenario.source?.type === 'route'
    ? `  // await page.goto(${quote(scenario.source.path)});`
    : '';
}

function cypressNavigation(scenario) {
  return scenario.source?.type === 'route'
    ? `  // cy.visit(${quote(scenario.source.path)});`
    : '';
}

function header(plan) {
  return `/**
 * Generated by AAFE test-agent from plan ${plan.id}.
 * Risk: ${plan.risk}${plan.requirement ? `\n * Requirement: ${plan.requirement}` : ''}
 *
 * These are skeletons, not passing tests: each case fails until a human or an
 * IDE agent fills in the real selectors and assertions.
 */`;
}

function describeTitle(plan) {
  return plan.requirement ? `AAFE: ${plan.requirement}` : 'AAFE generated coverage';
}

function fileStem(plan) {
  const base = plan.requirement || plan.id;
  return String(base)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40) || 'aafe';
}

function quote(value) {
  return JSON.stringify(String(value ?? ''));
}

function indent(text) {
  return text.split('\n').map((line) => (line ? `  ${line}` : line)).join('\n');
}
