/*
 * Tencent is pleased to support the open source community by making
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) available.
 * Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
 * 蓝鲸智云PaaS平台 (BlueKing PaaS) is licensed under the MIT License.
 * License for 蓝鲸智云PaaS平台 (BlueKing PaaS):
 * ---------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

import { renderFeatureCase, renderSmokeCase, isRealRoute, normalizeEntry } from '../../testing/e2e/yaml.js';
import { compileCaseToSpec } from '../../testing/e2e/compile.js';
import { parseCaseYaml } from '../../testing/e2e/yaml.js';

/**
 * Render runnable test artifacts from a test plan.
 *
 * E2E scenarios become AITest-compatible YAML (source of truth) plus compiled
 * Playwright specs under .aafe/e2e/specs. Unit/integration stay as skeletons.
 */
export function generateTests(plan, { e2eRunner = null, unitRunner = null, casesDir = 'tests/ui-ai/cases' } = {}) {
  const files = [];
  const e2eScenarios = plan.scenarios.filter((scenario) => scenario.kind === 'e2e');
  const otherScenarios = plan.scenarios.filter((scenario) => scenario.kind !== 'e2e');
  const usedIds = [];

  e2eScenarios.forEach((scenario, index) => {
    const entry = scenario.source?.path;
    if (!isRealRoute(entry)) return;
    const prefix = plan.scenario === 'coverage' && scenario.source?.type === 'feature' ? 'FEAT' : plan.pr ? 'PR' : 'CHG';
    const id = scenario.caseId && /^[A-Z][A-Z0-9_-]*-[0-9]{3}$/.test(scenario.caseId)
      ? scenario.caseId
      : `${prefix}-${String(index + 1).padStart(3, '0')}`;
    if (usedIds.includes(id)) return;
    usedIds.push(id);
    scenario.caseId = id;
    const yaml = scenario.source?.type === 'feature'
      ? renderFeatureCase(id, {
        title: scenario.title,
        entry,
        featureId: scenario.relatedFeature,
        sourcePath: scenario.source?.file
      })
      : renderSmokeCase(id, entry, {
        sourcePath: scenario.source?.file,
        sourceKind: plan.pr ? 'requirement' : 'quality-gate',
        sourceRef: plan.pr?.url ?? (plan.scenario === 'coverage' ? 'inventory-smoke' : 'change-smoke')
      });
    files.push({
      path: `${casesDir}/${id}.yaml`,
      runner: e2eRunner ?? 'playwright',
      kind: 'yaml',
      content: yaml
    });
    const compiled = compileCaseToSpec(parseCaseYaml(yaml));
    files.push({
      path: `.aafe/e2e/specs/${id}.spec.js`,
      runner: 'playwright',
      kind: 'spec',
      overwrite: true,
      content: compiled
    });
  });

  if (otherScenarios.length > 0) {
    const runner = unitRunner ?? 'vitest';
    files.push({
      path: `tests/aafe/${fileStem(plan)}.spec.js`,
      runner,
      kind: 'unit',
      content: renderUnit(otherScenarios, plan, runner)
    });
  }

  return files;
}

function renderUnit(scenarios, plan, runner) {
  const importLine = runner === 'jest'
    ? ''
    : "import { describe, expect, it } from 'vitest';\n";
  const body = scenarios.map((scenario) => `
it(${quote(scenario.title)}, () => {
${steps(scenario)}
${expectations(scenario)}
  expect.fail?.('AAFE generated this skeleton; replace with real assertions.')
    ?? expect(true, 'AAFE skeleton').toBe(false);
});`).join('\n');

  return `${header(plan)}
${importLine}
describe(${quote(describeTitle(plan))}, () => {
${indent(body)}
});
`;
}

function steps(scenario) {
  return scenario.steps.map((step) => `  // step: ${step}`).join('\n');
}

function expectations(scenario) {
  return scenario.expected.map((item) => `  // expect: ${item}`).join('\n');
}

function header(plan) {
  return `/**
 * Generated by AAFE test-agent from plan ${plan.id}.
 * Risk: ${plan.risk}${plan.requirement ? `\n * Requirement: ${plan.requirement}` : ''}
 *
 * These are skeletons, not passing tests: each case fails until a human or an
 * IDE agent fills in the real selectors and assertions.
 */`;
}

function describeTitle(plan) {
  return plan.requirement ? `AAFE: ${plan.requirement}` : 'AAFE generated coverage';
}

function fileStem(plan) {
  const base = plan.requirement || plan.id;
  return String(base)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40) || 'aafe';
}

function quote(value) {
  return JSON.stringify(String(value ?? ''));
}

function indent(text) {
  return text.split('\n').map((line) => (line ? `  ${line}` : line)).join('\n');
}
