/**
 * The frontend pattern catalog: 16 pattern domains covering 304 patterns,
 * plus the 155 domain rules that constrain their use.
 *
 * Two shapes live here and they serve different jobs. `PATTERN_DOMAINS` is the
 * full reference list, used to generate rule files and to route a problem to the
 * right domain. `PATTERN_INDEX` is the much smaller set the composer can
 * actually reason about, because scoring a pattern needs a cost model and
 * inventing one for all 304 would be fiction.
 */

/** @typedef {'architecture'|'creational'|'structural'|'behavioral'|'state'|'component'|'data'|'async'|'rendering'|'performance'|'resilience'|'integration'|'module'|'event'|'testing'|'migration'} PatternDomainId */

export const PATTERN_DOMAINS = Object.freeze([
  Object.freeze({
    id: 'architecture',
    order: 1,
    name: 'Architectural Patterns',
    rulePrefix: 'ARCH',
    patterns: Object.freeze(["Layered Architecture", "Clean Architecture", "Hexagonal Architecture", "Onion Architecture", "Feature-Sliced Architecture", "Modular Monolith", "Micro Frontend", "Plugin Architecture", "Event-Driven Architecture", "Pipe and Filter", "MVC", "MVP", "MVVM", "Flux", "Unidirectional Data Flow"]),
    rules: Object.freeze([
    { id: 'ARCH-001', text: "Architecture MUST be selected based on system constraints." },
    { id: 'ARCH-002', text: "Architecture MUST NOT be confused with a design pattern." },
    { id: 'ARCH-003', text: "Architecture defines large-scale dependency and responsibility boundaries." },
    { id: 'ARCH-004', text: "Architecture MUST NOT be selected only because it is popular." },
    { id: 'ARCH-005', text: "Micro Frontend MUST NOT be introduced without organizational or deployment boundaries." },
    { id: 'ARCH-006', text: "Clean Architecture MUST NOT become unnecessary abstraction." },
    { id: 'ARCH-007', text: "Feature boundaries SHOULD follow business capabilities when business complexity is high." },
    { id: 'ARCH-008', text: "UI components MUST NOT become the primary location of business rules." },
    { id: 'ARCH-009', text: "Dependency direction MUST be explicit." },
    { id: 'ARCH-010', text: "Architecture MUST optimize for changeability rather than directory aesthetics." }
    ])
  }),
  Object.freeze({
    id: 'creational',
    order: 2,
    name: 'Creational Patterns',
    rulePrefix: 'CREATIONAL',
    patterns: Object.freeze(["Factory Method", "Abstract Factory", "Builder", "Prototype", "Singleton", "Object Pool", "Dependency Injection", "Dependency Injection Container", "Service Locator", "Registry", "Factory Function", "Functional Factory"]),
    rules: Object.freeze([
    { id: 'CREATIONAL-001', text: "Factory MUST encapsulate meaningful creation variation." },
    { id: 'CREATIONAL-002', text: "Factory MUST NOT wrap trivial constructors." },
    { id: 'CREATIONAL-003', text: "Singleton MUST NOT be used merely for global access." },
    { id: 'CREATIONAL-004', text: "Global mutable state MUST NOT be disguised as Singleton." },
    { id: 'CREATIONAL-005', text: "DI MUST have a clear dependency boundary." },
    { id: 'CREATIONAL-006', text: "Service Locator SHOULD be avoided when it hides dependencies." },
    { id: 'CREATIONAL-007', text: "Builder SHOULD be used when object construction is genuinely complex." },
    { id: 'CREATIONAL-008', text: "Prototype SHOULD be used only when cloning semantics are meaningful." }
    ])
  }),
  Object.freeze({
    id: 'structural',
    order: 3,
    name: 'Structural Patterns',
    rulePrefix: 'STRUCTURAL',
    patterns: Object.freeze(["Adapter", "Bridge", "Composite", "Decorator", "Facade", "Flyweight", "Proxy", "Wrapper", "Module", "Layer", "Anti-Corruption Layer", "Data Mapper", "DTO", "View Model"]),
    rules: Object.freeze([
    { id: 'STRUCTURAL-001', text: "Adapter MUST translate incompatible interfaces." },
    { id: 'STRUCTURAL-002', text: "Facade MUST simplify a complex subsystem." },
    { id: 'STRUCTURAL-003', text: "Facade MUST NOT become a God Object." },
    { id: 'STRUCTURAL-004', text: "Decorator SHOULD preserve the wrapped component contract." },
    { id: 'STRUCTURAL-005', text: "Proxy MUST have an explicit interception purpose." },
    { id: 'STRUCTURAL-006', text: "Composite MUST represent meaningful tree structures." },
    { id: 'STRUCTURAL-007', text: "Flyweight SHOULD only be introduced when object duplication creates measurable cost." },
    { id: 'STRUCTURAL-008', text: "DTO MUST NOT automatically become a Domain Model." }
    ])
  }),
  Object.freeze({
    id: 'behavioral',
    order: 4,
    name: 'Behavioral Patterns',
    rulePrefix: 'BEHAVIORAL',
    patterns: Object.freeze(["Strategy", "State", "Command", "Observer", "Mediator", "Chain of Responsibility", "Template Method", "Visitor", "Iterator", "Interpreter", "Memento", "Null Object", "Policy", "Specification", "Rule Engine", "Pipeline", "Middleware", "Hook", "Callback"]),
    rules: Object.freeze([
    { id: 'BEHAVIORAL-001', text: "Strategy isolates interchangeable behavior." },
    { id: 'BEHAVIORAL-002', text: "State models behavior that changes according to state." },
    { id: 'BEHAVIORAL-003', text: "Strategy and State MUST NOT be confused." },
    { id: 'BEHAVIORAL-004', text: "Command encapsulates an action." },
    { id: 'BEHAVIORAL-005', text: "Command SHOULD be considered for Undo/Redo." },
    { id: 'BEHAVIORAL-006', text: "Observer MUST NOT create uncontrolled event chains." },
    { id: 'BEHAVIORAL-007', text: "Mediator SHOULD reduce direct peer-to-peer coupling." },
    { id: 'BEHAVIORAL-008', text: "Chain of Responsibility SHOULD be used for ordered processing." },
    { id: 'BEHAVIORAL-009', text: "Pipeline MUST explicitly define stage contracts." },
    { id: 'BEHAVIORAL-010', text: "Middleware MUST have a clear execution boundary." },
    { id: 'BEHAVIORAL-011', text: "Rule Engine SHOULD be used when rules change independently from orchestration." },
    { id: 'BEHAVIORAL-012', text: "Specification SHOULD represent reusable business predicates." }
    ])
  }),
  Object.freeze({
    id: 'state',
    order: 5,
    name: 'State Management Patterns',
    rulePrefix: 'STATE',
    patterns: Object.freeze(["Local State", "Lifted State", "Global State", "Derived State", "Server State", "Finite State Machine", "State Machine", "Reducer", "Event Sourcing", "CQRS", "Reactive State", "Observable State", "Actor Model", "Store", "Selector", "Command State", "Snapshot", "Undo/Redo", "Optimistic State", "Transactional State"]),
    rules: Object.freeze([
    { id: 'STATE-001', text: "State MUST have an explicit ownership boundary." },
    { id: 'STATE-002', text: "Do not globalize state merely because multiple components access it." },
    { id: 'STATE-003', text: "Derived state SHOULD NOT be duplicated as independent mutable state." },
    { id: 'STATE-004', text: "Server state SHOULD NOT automatically become client global state." },
    { id: 'STATE-005', text: "State transitions MUST be explicit for complex workflows." },
    { id: 'STATE-006', text: "Finite State Machine SHOULD be considered for state-heavy UI workflows." },
    { id: 'STATE-007', text: "Reducer MUST remain deterministic where its architectural role requires it." },
    { id: 'STATE-008', text: "Selectors SHOULD prevent unnecessary state coupling." },
    { id: 'STATE-009', text: "Optimistic state MUST define rollback behavior." },
    { id: 'STATE-010', text: "Undo/Redo MUST define history boundaries." },
    { id: 'STATE-011', text: "Event Sourcing MUST NOT be introduced simply because events exist." },
    { id: 'STATE-012', text: "CQRS MUST NOT be introduced merely because read/write operations differ." }
    ])
  }),
  Object.freeze({
    id: 'component',
    order: 6,
    name: 'Component Patterns',
    rulePrefix: 'COMPONENT',
    patterns: Object.freeze(["Container / Presentational", "Compound Component", "Controlled Component", "Uncontrolled Component", "Render Props", "Higher-Order Component", "Custom Hook", "Composable", "Provider", "Consumer", "Slot", "Headless Component", "Polymorphic Component", "Smart / Dumb Component", "Component Adapter", "Component Facade", "Component Registry", "Dynamic Component", "Portal", "Error Boundary", "Suspense Boundary"]),
    rules: Object.freeze([
    { id: 'COMPONENT-001', text: "Components SHOULD have explicit responsibility boundaries." },
    { id: 'COMPONENT-002', text: "Business logic SHOULD NOT be duplicated across components." },
    { id: 'COMPONENT-003', text: "Container / Presentational separation SHOULD only be introduced when it reduces complexity." },
    { id: 'COMPONENT-004', text: "Compound Components SHOULD be used for coordinated component APIs." },
    { id: 'COMPONENT-005', text: "Controlled Components SHOULD be preferred when state ownership must remain external." },
    { id: 'COMPONENT-006', text: "Headless Components SHOULD separate behavior from presentation." },
    { id: 'COMPONENT-007', text: "Hooks / Composables MUST NOT become unbounded service containers." },
    { id: 'COMPONENT-008', text: "Provider MUST have a clearly defined dependency scope." },
    { id: 'COMPONENT-009', text: "Component abstractions MUST be driven by repeated variation." },
    { id: 'COMPONENT-010', text: "Do not create a component abstraction for a single usage without meaningful reuse value." }
    ])
  }),
  Object.freeze({
    id: 'data',
    order: 7,
    name: 'Data Access Patterns',
    rulePrefix: 'DATA',
    patterns: Object.freeze(["Repository", "DAO", "Data Mapper", "Active Record", "Unit of Work", "Identity Map", "Cache Aside", "Read Through", "Write Through", "Write Behind", "CQRS", "DTO", "Serializer", "Deserializer", "Normalization", "Denormalization", "Pagination", "Cursor", "Lazy Loading", "Prefetch", "Batching"]),
    rules: Object.freeze([
    { id: 'DATA-001', text: "Data access MUST be separated from presentation when complexity requires it." },
    { id: 'DATA-002', text: "API response models MUST NOT automatically become UI models." },
    { id: 'DATA-003', text: "Repository MUST abstract meaningful data access behavior." },
    { id: 'DATA-004', text: "Do not create repositories for trivial one-line API wrappers." },
    { id: 'DATA-005', text: "Cache MUST define invalidation semantics." },
    { id: 'DATA-006', text: "Cache Aside MUST define source-of-truth behavior." },
    { id: 'DATA-007', text: "Lazy Loading MUST define loading and failure states." },
    { id: 'DATA-008', text: "Batching MUST preserve request semantics." },
    { id: 'DATA-009', text: "Pagination MUST define consistency behavior." },
    { id: 'DATA-010', text: "Normalization MUST only be introduced when duplicated entity state creates meaningful problems." }
    ])
  }),
  Object.freeze({
    id: 'async',
    order: 8,
    name: 'Async Patterns',
    rulePrefix: 'ASYNC',
    patterns: Object.freeze(["Promise", "Async/Await", "Future", "Observable", "Reactive Stream", "Pipeline", "Queue", "Scheduler", "Debounce", "Throttle", "Cancellation", "Retry", "Backoff", "Timeout", "Circuit Breaker", "Bulkhead", "Concurrency Limit", "Request Deduplication", "Request Coalescing", "Race Prevention", "Latest Wins", "First Wins", "Sequential Execution", "Parallel Execution", "Waterfall", "Prefetch", "Background Task", "Worker"]),
    rules: Object.freeze([
    { id: 'ASYNC-001', text: "Every asynchronous workflow MUST define failure behavior." },
    { id: 'ASYNC-002', text: "Long-running async operations SHOULD support cancellation when meaningful." },
    { id: 'ASYNC-003', text: "Retry MUST NOT be introduced without retryability analysis." },
    { id: 'ASYNC-004', text: "Retry MUST define maximum attempts." },
    { id: 'ASYNC-005', text: "Retry SHOULD use backoff where repeated requests may overload dependencies." },
    { id: 'ASYNC-006', text: "Concurrent requests MUST define race behavior." },
    { id: 'ASYNC-007', text: "Latest-Wins MUST be used intentionally, not accidentally." },
    { id: 'ASYNC-008', text: "Debounce and Throttle MUST NOT be treated as interchangeable." },
    { id: 'ASYNC-009', text: "Request deduplication MUST define cache/request lifecycle." },
    { id: 'ASYNC-010', text: "Parallel execution MUST define partial failure semantics." },
    { id: 'ASYNC-011', text: "Worker-based execution MUST define serialization boundaries." },
    { id: 'ASYNC-012', text: "Async state MUST remain consistent with UI lifecycle." }
    ])
  }),
  Object.freeze({
    id: 'rendering',
    order: 9,
    name: 'Rendering Patterns',
    rulePrefix: 'RENDER',
    patterns: Object.freeze(["CSR", "SSR", "SSG", "ISR", "Hydration", "Partial Hydration", "Progressive Hydration", "Streaming", "Islands Architecture", "Virtualization", "Windowing", "Incremental Rendering", "Progressive Rendering", "Lazy Rendering", "Offscreen Rendering", "Canvas Rendering", "WebGL Rendering", "Worker Rendering", "Double Buffering", "Layered Rendering", "Skeleton", "Placeholder", "Optimistic Rendering"]),
    rules: Object.freeze([
    { id: 'RENDER-001', text: "Rendering strategy MUST be selected according to data volume, interaction and runtime constraints." },
    { id: 'RENDER-002', text: "Virtualization SHOULD be considered for large collections." },
    { id: 'RENDER-003', text: "Virtualization MUST NOT be introduced where the data set is small and complexity outweighs benefit." },
    { id: 'RENDER-004', text: "Rendering MUST separate data lifecycle from visual lifecycle when needed." },
    { id: 'RENDER-005', text: "Heavy computation SHOULD be moved outside the rendering critical path." },
    { id: 'RENDER-006', text: "Canvas MUST NOT automatically replace DOM." },
    { id: 'RENDER-007', text: "SSR MUST define hydration behavior." },
    { id: 'RENDER-008', text: "Streaming MUST define progressive failure behavior." },
    { id: 'RENDER-009', text: "Skeleton UI MUST represent actual loading states rather than fake progress." },
    { id: 'RENDER-010', text: "Optimistic Rendering MUST define rollback behavior." }
    ])
  }),
  Object.freeze({
    id: 'performance',
    order: 10,
    name: 'Performance Patterns',
    rulePrefix: 'PERF',
    patterns: Object.freeze(["Memoization", "Caching", "Lazy Loading", "Code Splitting", "Tree Shaking", "Prefetching", "Preloading", "Virtualization", "Windowing", "Batching", "Debouncing", "Throttling", "Object Pooling", "Flyweight", "Structural Sharing", "Immutable Update", "Incremental Computation", "Incremental Rendering", "Worker Offloading", "WebAssembly", "Offscreen Processing", "Resource Pool", "Connection Pool", "Backpressure"]),
    rules: Object.freeze([
    { id: 'PERF-001', text: "Performance patterns MUST be driven by measurable bottlenecks." },
    { id: 'PERF-002', text: "Do not introduce optimization patterns without identifying the bottleneck." },
    { id: 'PERF-003', text: "Memoization MUST define cache lifetime." },
    { id: 'PERF-004', text: "Caching MUST define invalidation." },
    { id: 'PERF-005', text: "Code splitting MUST consider network and interaction costs." },
    { id: 'PERF-006', text: "Virtualization MUST define measurement strategy." },
    { id: 'PERF-007', text: "Worker offloading MUST account for serialization and transfer costs." },
    { id: 'PERF-008', text: "WebAssembly MUST only be introduced when computation characteristics justify it." },
    { id: 'PERF-009', text: "Object pooling MUST only be introduced when allocation pressure is meaningful." },
    { id: 'PERF-010', text: "Optimization MUST NOT materially increase architectural complexity without measurable benefit." }
    ])
  }),
  Object.freeze({
    id: 'resilience',
    order: 11,
    name: 'Resilience Patterns',
    rulePrefix: 'RESILIENCE',
    patterns: Object.freeze(["Error Boundary", "Retry", "Backoff", "Timeout", "Circuit Breaker", "Bulkhead", "Fallback", "Graceful Degradation", "Offline First", "Offline Fallback", "Cache", "Stale While Revalidate", "Optimistic Update", "Rollback", "Recovery", "Dead Letter", "Idempotency", "Rate Limiting", "Backpressure"]),
    rules: Object.freeze([
    { id: 'RESILIENCE-001', text: "Every external dependency SHOULD define failure behavior." },
    { id: 'RESILIENCE-002', text: "Retry MUST only apply to retryable failures." },
    { id: 'RESILIENCE-003', text: "Circuit Breaker MUST define open/closed/half-open behavior." },
    { id: 'RESILIENCE-004', text: "Fallback MUST preserve user-visible correctness." },
    { id: 'RESILIENCE-005', text: "Graceful degradation MUST define reduced functionality." },
    { id: 'RESILIENCE-006', text: "Offline-first MUST define synchronization conflict handling." },
    { id: 'RESILIENCE-007', text: "Optimistic updates MUST define rollback." },
    { id: 'RESILIENCE-008', text: "Idempotency MUST be defined for retryable mutations." },
    { id: 'RESILIENCE-009', text: "Error boundaries MUST define recovery scope." },
    { id: 'RESILIENCE-010', text: "Failures MUST NOT be silently swallowed." }
    ])
  }),
  Object.freeze({
    id: 'integration',
    order: 12,
    name: 'Integration Patterns',
    rulePrefix: 'INTEGRATION',
    patterns: Object.freeze(["Adapter", "Anti-Corruption Layer", "Facade", "Gateway", "BFF", "API Gateway", "Backend for Frontend", "Open Host Service", "Published Language", "Event Bus", "Message Bus", "Pub/Sub", "WebSocket", "SSE", "Polling", "Long Polling", "Webhook", "PostMessage", "BroadcastChannel", "Shared Worker", "Service Worker"]),
    rules: Object.freeze([
    { id: 'INTEGRATION-001', text: "External API contracts MUST NOT automatically become internal domain contracts." },
    { id: 'INTEGRATION-002', text: "Adapters SHOULD isolate external contract changes." },
    { id: 'INTEGRATION-003', text: "Integration failures MUST be isolated from core UI behavior." },
    { id: 'INTEGRATION-004', text: "Event-driven integration MUST define event ownership." },
    { id: 'INTEGRATION-005', text: "Cross-context communication MUST define contract versioning." },
    { id: 'INTEGRATION-006', text: "BFF SHOULD be introduced only when frontend-specific aggregation is needed." },
    { id: 'INTEGRATION-007', text: "Polling MUST define interval and termination conditions." },
    { id: 'INTEGRATION-008', text: "WebSocket MUST define reconnect behavior." },
    { id: 'INTEGRATION-009', text: "Service Worker MUST define cache ownership and invalidation." }
    ])
  }),
  Object.freeze({
    id: 'module',
    order: 13,
    name: 'Module Patterns',
    rulePrefix: 'MODULE',
    patterns: Object.freeze(["ES Module", "Namespace", "Barrel", "Facade Module", "Feature Module", "Domain Module", "Layer Module", "Dependency Injection", "Plugin", "Registry", "Dynamic Import", "Module Federation", "Micro Frontend", "Package Boundary", "Public API", "Internal API"]),
    rules: Object.freeze([
    { id: 'MODULE-001', text: "Every module SHOULD have an explicit public API." },
    { id: 'MODULE-002', text: "Internal implementation MUST NOT be exposed unnecessarily." },
    { id: 'MODULE-003', text: "Barrel exports MUST NOT create circular dependencies." },
    { id: 'MODULE-004', text: "Feature boundaries SHOULD reflect business or user-facing capabilities when appropriate." },
    { id: 'MODULE-005', text: "Dynamic module loading MUST define lifecycle." },
    { id: 'MODULE-006', text: "Plugin systems MUST define extension contracts." },
    { id: 'MODULE-007', text: "Module Federation MUST NOT be introduced solely for technical novelty." },
    { id: 'MODULE-008', text: "Cross-module dependencies MUST be explicit." }
    ])
  }),
  Object.freeze({
    id: 'event',
    order: 14,
    name: 'Event Patterns',
    rulePrefix: 'EVENT',
    patterns: Object.freeze(["Observer", "Event Emitter", "Pub/Sub", "Event Bus", "Domain Event", "Integration Event", "Command Bus", "Message Bus", "Event Queue", "Event Stream", "Event Sourcing", "Mediator", "Broadcast", "Reactive Stream"]),
    rules: Object.freeze([
    { id: 'EVENT-001', text: "Event MUST have a clearly defined owner." },
    { id: 'EVENT-002', text: "Event name MUST represent a meaningful occurrence or command." },
    { id: 'EVENT-003', text: "Event payload MUST have a stable contract." },
    { id: 'EVENT-004', text: "Event listeners MUST define lifecycle." },
    { id: 'EVENT-005', text: "Global Event Bus SHOULD NOT become uncontrolled application state." },
    { id: 'EVENT-006', text: "Events MUST NOT replace direct function calls without a coupling problem." },
    { id: 'EVENT-007', text: "Event-driven flows MUST provide tracing capability." },
    { id: 'EVENT-008', text: "Event ordering MUST be defined where required." },
    { id: 'EVENT-009', text: "Event duplication MUST be considered." },
    { id: 'EVENT-010', text: "Event-driven architecture MUST define failure semantics." }
    ])
  }),
  Object.freeze({
    id: 'testing',
    order: 15,
    name: 'Testing Patterns',
    rulePrefix: 'TEST',
    patterns: Object.freeze(["Test Pyramid", "Testing Trophy", "Unit Test", "Component Test", "Integration Test", "Contract Test", "E2E", "Snapshot", "Golden Master", "Characterization Test", "Property-Based Testing", "Mutation Testing", "Test Double", "Mock", "Stub", "Spy", "Fake", "Fixture", "Test Data Builder", "Object Mother", "Page Object", "Screenplay Pattern", "Contract Testing"]),
    rules: Object.freeze([
    { id: 'TEST-001', text: "Tests SHOULD validate behavior rather than implementation details." },
    { id: 'TEST-002', text: "Mocks SHOULD NOT replace meaningful integration verification." },
    { id: 'TEST-003', text: "Characterization Tests SHOULD be considered before large refactoring." },
    { id: 'TEST-004', text: "Contract Tests SHOULD protect integration boundaries." },
    { id: 'TEST-005', text: "Test Data Builders SHOULD be used when test object construction becomes complex." },
    { id: 'TEST-006', text: "Snapshots MUST NOT replace semantic assertions." },
    { id: 'TEST-007', text: "E2E tests SHOULD focus on critical user journeys." },
    { id: 'TEST-008', text: "Pattern refactoring MUST include regression validation." }
    ])
  }),
  Object.freeze({
    id: 'migration',
    order: 16,
    name: 'Migration Patterns',
    rulePrefix: 'MIGRATION',
    patterns: Object.freeze(["Strangler Fig", "Branch by Abstraction", "Parallel Run", "Anti-Corruption Layer", "Facade Migration", "Adapter Migration", "Incremental Migration", "Feature Toggle", "Dark Launch", "Shadow Traffic", "Dual Write", "Read Migration", "Compatibility Layer", "Modularization"]),
    rules: Object.freeze([
    { id: 'MIGRATION-001', text: "Large architecture migration MUST be incremental unless explicitly justified." },
    { id: 'MIGRATION-002', text: "Branch by Abstraction SHOULD isolate replacement implementations." },
    { id: 'MIGRATION-003', text: "Strangler migration MUST define the replacement boundary." },
    { id: 'MIGRATION-004', text: "Dual Write MUST define consistency and rollback strategy." },
    { id: 'MIGRATION-005', text: "Compatibility layers MUST have an explicit removal strategy." },
    { id: 'MIGRATION-006', text: "Feature flags MUST define ownership and cleanup." },
    { id: 'MIGRATION-007', text: "Migration MUST preserve existing behavior by default." },
    { id: 'MIGRATION-008', text: "Every migration phase MUST have validation criteria." }
    ])
  })
]);

/**
 * Patterns the composer can score and combine.
 *
 * Fields, per the scoring model:
 * - `signals`   problem vocabulary that suggests this pattern is relevant
 * - `benefit`   changeIsolation / complexityReduction / reuse / performance, each 0-3
 * - `cost`      implementation / cognitive / coupling, each 0-3
 * - `justifiedAt` minimum problem complexity (1 simple, 2 moderate, 3 complex)
 *                below which introducing the pattern is over-engineering
 * - `conflictsWith` patterns that claim the same responsibility
 * - `requires`  patterns this one is incomplete without
 * - `flowsTo`   typical downstream collaborator, used to draw the composition graph
 */
export const PATTERN_INDEX = Object.freeze([
  // --- architecture ---
  p('layered-architecture', 'Layered Architecture', 'architecture', 'dependency-direction',
    '依赖方向混乱，业务规则散落在 UI 与基础设施中',
    ['分层', 'layer', '依赖方向', '架构', 'architecture', '解耦'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { flowsTo: ['facade'] }),
  p('plugin-architecture', 'Plugin Architecture', 'architecture', 'extension-surface',
    '第三方或业务方需要在不改核心代码的前提下扩展能力',
    ['插件', 'plugin', '扩展点', 'extension', '开放能力'],
    { changeIsolation: 3, complexityReduction: 0, reuse: 3, performance: 0 }, { implementation: 3, cognitive: 2, coupling: 1 }, 3,
    { requires: ['registry'], flowsTo: ['registry'] }),
  p('micro-frontend', 'Micro Frontend', 'architecture', 'deployment-boundary',
    '多团队独立开发部署同一产品',
    ['微前端', 'micro frontend', '独立部署', 'qiankun', 'module federation'],
    { changeIsolation: 3, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 3, cognitive: 3, coupling: 2 }, 3,
    { conflictsWith: ['modular-monolith'] }),
  p('modular-monolith', 'Modular Monolith', 'architecture', 'module-boundary',
    '需要清晰模块边界但没有独立部署诉求',
    ['模块化', 'modular', '单体', 'monolith', '模块边界'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { conflictsWith: ['micro-frontend'] }),
  p('unidirectional-data-flow', 'Unidirectional Data Flow', 'architecture', 'data-direction',
    '状态变更来源不明，难以追踪谁改了什么',
    ['单向数据流', 'unidirectional', 'flux', '数据流', '可追踪'],
    { changeIsolation: 2, complexityReduction: 3, reuse: 0, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { flowsTo: ['reducer'] }),

  // --- creational ---
  p('factory', 'Factory', 'creational', 'object-creation',
    '创建逻辑随类型变化，调用方不应关心具体构造',
    ['工厂', 'factory', '创建', 'create', '实例化', '多种类型'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { alternatives: ['builder'] }),
  p('builder', 'Builder', 'creational', 'complex-construction',
    '对象构造步骤多、可选参数多',
    ['builder', '构造', '可选参数', '分步构建'],
    { changeIsolation: 1, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { alternatives: ['factory'] }),
  p('registry', 'Registry', 'creational', 'extension-lookup',
    '能力需要被注册、查找与替换',
    ['注册', 'registry', '扩展', '插件', 'component map', '查找表'],
    { changeIsolation: 3, complexityReduction: 1, reuse: 3, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 1 }, 2,
    { flowsTo: ['factory'] }),
  p('dependency-injection', 'Dependency Injection', 'creational', 'dependency-wiring',
    '依赖硬编码导致无法替换与测试',
    ['依赖注入', 'dependency injection', 'di', 'provide', 'inject', '可测试'],
    { changeIsolation: 3, complexityReduction: 0, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 2, coupling: 0 }, 2,
    { conflictsWith: ['service-locator'] }),
  p('service-locator', 'Service Locator', 'creational', 'dependency-lookup',
    '集中查找依赖，但会隐藏依赖关系',
    ['service locator', '服务定位'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 2, coupling: 3 }, 3,
    { conflictsWith: ['dependency-injection'], alternatives: ['dependency-injection'] }),
  p('singleton', 'Singleton', 'creational', 'single-instance',
    '确实只能存在一个实例（连接池、全局调度器）',
    ['单例', 'singleton', '全局唯一'],
    { changeIsolation: 0, complexityReduction: 1, reuse: 0, performance: 1 }, { implementation: 0, cognitive: 1, coupling: 3 }, 3,
    {}),

  // --- structural ---
  p('adapter', 'Adapter', 'structural', 'external-boundary',
    '外部 API 形状与内部模型不一致',
    ['adapter', '适配', '第三方', 'third-party', '兼容', 'wrapper', '外部接口'],
    { changeIsolation: 3, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { flowsTo: ['retry'] }),
  p('anti-corruption-layer', 'Anti-Corruption Layer', 'structural', 'model-protection',
    '外部模型正在污染内部领域模型',
    ['防腐层', 'anti-corruption', 'acl', '模型污染', '遗留系统'],
    { changeIsolation: 3, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 3,
    { requires: ['adapter'] }),
  p('facade', 'Facade', 'structural', 'entry-surface',
    '调用方需要面对过多子系统细节',
    ['facade', '门面', '统一入口', '简化接口', 'api 聚合'],
    { changeIsolation: 2, complexityReduction: 3, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 0, coupling: 1 }, 2,
    { flowsTo: ['command'] }),
  p('composite', 'Composite', 'structural', 'tree-structure',
    '需要以统一方式处理叶子与容器',
    ['composite', '树形', '嵌套', 'tree', '递归结构'],
    { changeIsolation: 1, complexityReduction: 2, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('decorator', 'Decorator', 'structural', 'behavior-augmentation',
    '需要在不改原实现的前提下叠加行为',
    ['decorator', '装饰', '增强', '包装', 'middleware'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 2, coupling: 0 }, 2,
    {}),
  p('proxy', 'Proxy', 'structural', 'access-control',
    '访问需要被拦截：懒加载、鉴权、埋点',
    ['proxy', '代理', '拦截', '懒加载', '鉴权'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 1 }, { implementation: 1, cognitive: 2, coupling: 0 }, 2,
    {}),

  // --- behavioral ---
  p('strategy', 'Strategy', 'behavioral', 'algorithm-variation',
    '同一能力存在多种可替换实现，需要运行时选择或后续扩展',
    ['策略', 'strategy', '多种算法', '可替换', '多种实现', '布局', 'layout', '排序', '计价', 'policy'],
    { changeIsolation: 3, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { alternatives: ['chain-of-responsibility'] }),
  p('state-machine', 'State Machine', 'behavioral', 'workflow-state',
    '状态多、流转规则明确、非法状态必须被禁止',
    ['状态机', 'state machine', '状态流转', 'workflow', '审批', '多步骤', 'wizard', '生命周期'],
    { changeIsolation: 2, complexityReduction: 3, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { conflictsWith: ['reducer'], flowsTo: ['command'] }),
  p('command', 'Command', 'behavioral', 'user-operation',
    '用户操作需要记录、回放、撤销、重做或审计',
    ['command', '命令', 'undo', 'redo', '撤销', '重做', '操作记录', '审计', 'history'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { flowsTo: ['repository'] }),
  p('observer', 'Observer', 'behavioral', 'change-notification',
    '一处变化需要通知多个订阅方，发布方不应依赖订阅方',
    ['observer', '订阅', 'subscribe', '监听', '通知', 'publish', '响应式'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 2, coupling: 2 }, 2,
    { conflictsWith: ['event-bus'] }),
  p('mediator', 'Mediator', 'behavioral', 'interaction-hub',
    '多个组件两两通信导致网状依赖',
    ['mediator', '中介', '协调', '网状依赖', '组件通信'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 0, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 2 }, 3,
    { conflictsWith: ['event-bus'] }),
  p('chain-of-responsibility', 'Chain of Responsibility', 'behavioral', 'sequential-handling',
    '请求需要按顺序交给可能处理它的多个处理者',
    ['责任链', 'chain of responsibility', '拦截器', '逐级处理'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 2, coupling: 0 }, 3,
    { alternatives: ['pipeline'] }),
  p('pipeline', 'Pipeline', 'behavioral', 'staged-processing',
    '任务由稳定的多个阶段串联，每阶段可插拔或可观测',
    ['pipeline', '流水线', '步骤', '链路', '处理流程', 'transform', 'middleware', '校验链'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { alternatives: ['chain-of-responsibility'] }),
  p('specification', 'Specification', 'behavioral', 'reusable-predicate',
    '业务判定条件被复制粘贴到多处',
    ['specification', '规约', '业务规则', '判定条件', 'rule engine', '规则引擎'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 3, performance: 0 }, { implementation: 2, cognitive: 2, coupling: 0 }, 3,
    {}),

  // --- state ---
  p('reducer', 'Reducer', 'state', 'state-transition',
    '状态更新分散，难以追踪与测试',
    ['reducer', 'redux', 'vuex', 'pinia', 'dispatch', 'action', '状态更新'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { conflictsWith: ['state-machine'] }),
  p('server-state', 'Server State', 'state', 'remote-cache',
    '服务端数据被当作本地状态手工同步',
    ['server state', 'react-query', 'swr', 'tanstack', '数据请求', '缓存失效', '接口数据'],
    { changeIsolation: 2, complexityReduction: 3, reuse: 2, performance: 2 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    { conflictsWith: ['global-state'], flowsTo: ['cache-aside'] }),
  p('global-state', 'Global State', 'state', 'shared-state',
    '跨页面共享的少量真正全局状态',
    ['全局状态', 'global state', 'global store', '跨页面共享'],
    { changeIsolation: 0, complexityReduction: 1, reuse: 1, performance: 0 }, { implementation: 0, cognitive: 2, coupling: 3 }, 3,
    { conflictsWith: ['server-state'], alternatives: ['lifted-state', 'server-state'] }),
  p('lifted-state', 'Lifted State', 'state', 'local-sharing',
    '少数兄弟组件需要共享状态',
    ['状态提升', 'lifted state', '父组件状态', 'props'],
    { changeIsolation: 1, complexityReduction: 2, reuse: 0, performance: 0 }, { implementation: 0, cognitive: 0, coupling: 1 }, 1,
    {}),
  p('derived-state', 'Derived State', 'state', 'computed-view',
    '派生数据被冗余存储导致不一致',
    ['派生状态', 'derived', 'computed', 'selector', '计算属性'],
    { changeIsolation: 1, complexityReduction: 3, reuse: 1, performance: 1 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('undo-redo', 'Undo/Redo', 'state', 'history-navigation',
    '用户需要撤销与重做操作',
    ['undo', 'redo', '撤销', '重做', '历史记录'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 3, cognitive: 1, coupling: 0 }, 2,
    { requires: ['command'] }),
  p('optimistic-state', 'Optimistic State', 'state', 'perceived-latency',
    '交互需要立即反馈，不等服务端确认',
    ['乐观更新', 'optimistic', '立即反馈', '先更新后同步'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 3 }, { implementation: 2, cognitive: 2, coupling: 0 }, 2,
    { requires: ['rollback'] }),
  p('event-sourcing', 'Event Sourcing', 'state', 'append-only-history',
    '必须保留状态变更的完整历史',
    ['event sourcing', '事件溯源', '变更历史', '审计追溯'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 3, cognitive: 3, coupling: 0 }, 3,
    { requires: ['domain-event'] }),
  p('cqrs', 'CQRS', 'state', 'read-write-split',
    '读模型与写模型的形状和负载差异极大',
    ['cqrs', '读写分离', '查询模型', '命令模型'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 0, performance: 2 }, { implementation: 3, cognitive: 3, coupling: 0 }, 3,
    {}),

  // --- component ---
  p('container-presentational', 'Container / Presentational', 'component', 'ui-logic-split',
    '数据获取逻辑与渲染逻辑纠缠，组件无法复用与测试',
    ['容器组件', 'container', 'presentational', '展示组件', '逻辑分离'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 3, performance: 0 }, { implementation: 1, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('headless-component', 'Headless Component', 'component', 'behavior-without-ui',
    '同一交互行为需要多套视觉呈现',
    ['headless', '无头组件', '行为复用', '自定义渲染', 'render props'],
    { changeIsolation: 3, complexityReduction: 1, reuse: 3, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('compound-component', 'Compound Component', 'component', 'composable-ui',
    '组件配置项爆炸，props 无法表达灵活布局',
    ['compound', '复合组件', 'slot', 'children', '组合式 api'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 3, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('custom-hook', 'Custom Hook / Composable', 'component', 'stateful-logic-reuse',
    '有状态逻辑在多个组件间重复',
    ['hook', 'composable', '自定义 hook', '逻辑复用', 'use'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 3, performance: 0 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('provider', 'Provider / Context', 'component', 'scoped-dependency',
    '深层组件需要访问共享依赖，逐层传递不可维护',
    ['provider', 'context', '注入', 'provide', 'prop drilling', '逐层传递'],
    { changeIsolation: 1, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 2 }, 2,
    {}),
  p('error-boundary', 'Error Boundary', 'component', 'failure-containment',
    '局部渲染异常导致整页白屏',
    ['error boundary', '错误边界', '白屏', '兜底', '异常捕获'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 0, coupling: 0 }, 1,
    { flowsTo: ['fallback'] }),

  // --- data ---
  p('repository', 'Repository', 'data', 'data-access',
    '数据访问细节散落在组件与业务代码中',
    ['repository', '仓储', '数据访问', '持久化', '数据源'],
    { changeIsolation: 3, complexityReduction: 1, reuse: 2, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { flowsTo: ['adapter', 'cache-aside'] }),
  p('data-mapper', 'Data Mapper', 'data', 'model-translation',
    '接口结构与视图模型形状不一致',
    ['data mapper', '数据映射', 'dto', '模型转换', '字段映射'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 2, performance: 0 }, { implementation: 1, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('cache-aside', 'Cache Aside', 'data', 'read-cache',
    '重复请求相同数据造成浪费',
    ['缓存', 'cache', '缓存穿透', '重复请求', '本地缓存'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 1, cognitive: 2, coupling: 0 }, 2,
    {}),
  p('normalization', 'Normalization', 'data', 'entity-store',
    '同一实体在多处冗余存储导致不一致',
    ['归一化', 'normalize', '实体表', '数据冗余', '一致性'],
    { changeIsolation: 1, complexityReduction: 2, reuse: 1, performance: 1 }, { implementation: 2, cognitive: 2, coupling: 0 }, 3,
    {}),
  p('pagination', 'Pagination', 'data', 'bounded-fetch',
    '一次性拉取全量数据不可行',
    ['分页', 'pagination', '滚动加载', 'cursor', '无限滚动'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 1, cognitive: 0, coupling: 0 }, 1,
    {}),

  // --- async ---
  p('debounce', 'Debounce', 'async', 'input-rate-limit',
    '高频输入触发过多请求或计算',
    ['防抖', 'debounce', '输入频繁', '搜索联想'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    { alternatives: ['throttle'] }),
  p('throttle', 'Throttle', 'async', 'event-rate-limit',
    '高频事件导致渲染或计算压力',
    ['节流', 'throttle', '滚动', 'resize', '高频事件'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    { alternatives: ['debounce'] }),
  p('cancellation', 'Cancellation', 'async', 'stale-response',
    '过期请求覆盖了最新结果',
    ['取消', 'cancel', 'abort', 'abortcontroller', '竞态', 'race'],
    { changeIsolation: 0, complexityReduction: 1, reuse: 1, performance: 1 }, { implementation: 1, cognitive: 1, coupling: 0 }, 1,
    {}),
  p('retry', 'Retry', 'async', 'transient-failure',
    '瞬时故障导致请求失败',
    ['重试', 'retry', '失败重发', 'backoff', '退避'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 1,
    { requires: ['timeout'], flowsTo: ['circuit-breaker'] }),
  p('timeout', 'Timeout', 'async', 'bounded-wait',
    '请求可能永远挂起',
    ['超时', 'timeout', '挂起', '无响应'],
    { changeIsolation: 0, complexityReduction: 1, reuse: 1, performance: 1 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('circuit-breaker', 'Circuit Breaker', 'async', 'failure-isolation',
    '持续失败的下游拖垮整个前端',
    ['熔断', 'circuit breaker', '雪崩', '持续失败'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 1 }, { implementation: 2, cognitive: 2, coupling: 0 }, 3,
    { requires: ['fallback'] }),
  p('request-deduplication', 'Request Deduplication', 'async', 'duplicate-suppression',
    '同一请求被并发发起多次',
    ['去重', 'dedupe', 'deduplication', '重复请求', '并发相同请求'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 2 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('concurrency-limit', 'Concurrency Limit', 'async', 'parallel-bound',
    '并发过高压垮浏览器或服务端',
    ['并发限制', 'concurrency', '并发数', '限流', '队列'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 2 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),

  // --- rendering ---
  p('virtualization', 'Virtualization', 'rendering', 'large-list',
    '长列表一次性渲染导致卡顿',
    ['虚拟列表', 'virtual', 'virtualization', 'windowing', '长列表', '大量数据', '万级'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('ssr', 'Server-Side Rendering', 'rendering', 'first-paint',
    '首屏时间与 SEO 不达标',
    ['ssr', '服务端渲染', '首屏', 'seo', 'nuxt', 'next'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 3 }, { implementation: 3, cognitive: 2, coupling: 1 }, 3,
    { flowsTo: ['progressive-hydration'] }),
  p('progressive-hydration', 'Progressive Hydration', 'rendering', 'interaction-readiness',
    '整页 hydration 阻塞交互',
    ['hydration', '渐进水合', 'islands', '可交互时间', 'tti'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 2 }, { implementation: 3, cognitive: 3, coupling: 0 }, 3,
    {}),
  p('skeleton', 'Skeleton / Placeholder', 'rendering', 'perceived-loading',
    '加载期间布局跳动、白屏感强',
    ['骨架屏', 'skeleton', 'placeholder', '加载态', '闪烁'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 1 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),

  // --- performance ---
  p('memoization', 'Memoization', 'performance', 'recompute-avoidance',
    '相同输入被反复计算',
    ['memo', 'memoization', '缓存计算', 'usememo', 'computed', '重复计算'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 2 }, { implementation: 0, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('code-splitting', 'Code Splitting', 'performance', 'bundle-size',
    '首包体积过大',
    ['代码分割', 'code splitting', '按需加载', '懒加载', '首包', 'bundle'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 3 }, { implementation: 1, cognitive: 0, coupling: 0 }, 1,
    { flowsTo: ['dynamic-import'] }),
  p('batching', 'Batching', 'performance', 'update-coalescing',
    '细碎更新触发过多渲染或请求',
    ['批量', 'batch', '合并请求', '合并更新'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 2 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('worker-offloading', 'Worker Offloading', 'performance', 'main-thread-relief',
    '重计算阻塞主线程',
    ['worker', 'web worker', '主线程', '阻塞', '重计算'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 3, cognitive: 2, coupling: 0 }, 3,
    {}),

  // --- resilience ---
  p('fallback', 'Fallback / Graceful Degradation', 'resilience', 'degraded-path',
    '依赖不可用时功能完全不可用',
    ['降级', 'fallback', '兜底', '容错', 'graceful degradation'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 1,
    {}),
  p('stale-while-revalidate', 'Stale While Revalidate', 'resilience', 'freshness-tradeoff',
    '每次都等最新数据导致体验差',
    ['swr', 'stale while revalidate', '先旧后新', '后台刷新'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 3 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('rollback', 'Rollback', 'resilience', 'failure-recovery',
    '乐观更新失败后状态不一致',
    ['回滚', 'rollback', '撤回', '恢复'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('idempotency', 'Idempotency', 'resilience', 'safe-retry',
    '重试导致重复提交',
    ['幂等', 'idempotency', '重复提交', '去重键'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 1, coupling: 0 }, 2,
    {}),

  // --- integration ---
  p('bff', 'Backend for Frontend', 'integration', 'api-shaping',
    '前端需要聚合多个后端接口',
    ['bff', 'backend for frontend', '接口聚合', '网关', 'gateway'],
    { changeIsolation: 2, complexityReduction: 2, reuse: 0, performance: 2 }, { implementation: 3, cognitive: 1, coupling: 1 }, 3,
    {}),
  p('event-bus', 'Event Bus', 'integration', 'decoupled-messaging',
    '互不相识的模块之间需要通信',
    ['event bus', '事件总线', 'eventemitter', 'pub/sub', '发布订阅', '广播'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 3, coupling: 3 }, 3,
    { conflictsWith: ['observer', 'mediator'] }),
  p('websocket', 'WebSocket / SSE', 'integration', 'server-push',
    '需要服务端主动推送',
    ['websocket', 'sse', '推送', '实时', 'realtime', '长连接'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 2 }, { implementation: 2, cognitive: 2, coupling: 1 }, 2,
    { alternatives: ['polling'], requires: ['fallback'] }),
  p('polling', 'Polling', 'integration', 'pull-refresh',
    '需要周期性获取最新数据但不值得长连接',
    ['轮询', 'polling', '定时刷新', 'interval'],
    { changeIsolation: 0, complexityReduction: 1, reuse: 0, performance: 0 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    { alternatives: ['websocket'] }),

  // --- module ---
  p('feature-module', 'Feature Module', 'module', 'feature-boundary',
    '按技术类型分目录导致一个需求改十个文件夹',
    ['feature module', '按功能分', '特性目录', 'feature-sliced', '模块划分'],
    { changeIsolation: 3, complexityReduction: 2, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 0, coupling: 0 }, 2,
    {}),
  p('public-api', 'Public API / Barrel', 'module', 'module-surface',
    '模块内部实现被外部随意引用',
    ['public api', 'barrel', 'index.ts', '对外接口', '模块出口'],
    { changeIsolation: 2, complexityReduction: 1, reuse: 1, performance: 0 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('dynamic-import', 'Dynamic Import', 'module', 'deferred-load',
    '低频模块被打进首包',
    ['动态导入', 'dynamic import', '异步组件', 'import()'],
    { changeIsolation: 0, complexityReduction: 0, reuse: 0, performance: 2 }, { implementation: 0, cognitive: 0, coupling: 0 }, 1,
    {}),
  p('module-federation', 'Module Federation', 'module', 'runtime-sharing',
    '多个独立构建的应用需要运行时共享模块',
    ['module federation', '模块联邦', '运行时共享', '远程模块'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 2, performance: 0 }, { implementation: 3, cognitive: 3, coupling: 2 }, 3,
    {}),

  // --- event ---
  p('domain-event', 'Domain Event', 'event', 'business-occurrence',
    '业务上有意义的变化需要被其他模块感知',
    ['领域事件', 'domain event', '业务事件', '变更通知'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 2, coupling: 1 }, 3,
    {}),
  p('command-bus', 'Command Bus', 'event', 'command-dispatch',
    '命令的发起方与处理方需要解耦',
    ['command bus', '命令总线', '命令分发'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 2, coupling: 1 }, 3,
    { requires: ['command'] }),

  // --- testing ---
  p('test-double', 'Test Double', 'testing', 'dependency-isolation',
    '测试依赖真实外部系统导致缓慢与不稳定',
    ['mock', 'stub', 'spy', 'fake', '测试替身', '打桩'],
    { changeIsolation: 1, complexityReduction: 1, reuse: 1, performance: 1 }, { implementation: 1, cognitive: 1, coupling: 1 }, 1,
    {}),
  p('contract-test', 'Contract Test', 'testing', 'boundary-agreement',
    '前后端接口契约变更无人察觉',
    ['契约测试', 'contract test', '接口契约', 'schema 校验'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('characterization-test', 'Characterization Test', 'testing', 'legacy-safety-net',
    '重构遗留代码时缺少行为基准',
    ['characterization', '特征测试', '遗留代码', '重构保护', '行为基准'],
    { changeIsolation: 1, complexityReduction: 0, reuse: 0, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 1,
    {}),

  // --- migration ---
  p('strangler-fig', 'Strangler Fig', 'migration', 'incremental-replacement',
    '旧系统无法一次性替换',
    ['绞杀', 'strangler', '渐进替换', '增量迁移', '并行运行'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 0, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    { requires: ['characterization-test'] }),
  p('branch-by-abstraction', 'Branch by Abstraction', 'migration', 'in-place-swap',
    '需要在主干上替换实现而不长期拉分支',
    ['branch by abstraction', '抽象分支', '双实现', '主干开发'],
    { changeIsolation: 3, complexityReduction: 0, reuse: 0, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 0 }, 2,
    {}),
  p('feature-toggle', 'Feature Toggle', 'migration', 'runtime-switch',
    '新旧实现需要可随时切换与灰度',
    ['feature toggle', '开关', '灰度', 'feature flag', '降级开关'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 1, performance: 0 }, { implementation: 1, cognitive: 2, coupling: 1 }, 1,
    {}),
  p('compatibility-layer', 'Compatibility Layer', 'migration', 'legacy-bridge',
    '迁移期间新旧模型必须共存',
    ['兼容层', 'compatibility', '过渡层', '新旧共存'],
    { changeIsolation: 2, complexityReduction: 0, reuse: 0, performance: 0 }, { implementation: 2, cognitive: 1, coupling: 1 }, 2,
    { requires: ['adapter'] })
]);

/** @type {Map<string, object>} */
export const PATTERN_BY_ID = new Map(PATTERN_INDEX.map((entry) => [entry.id, entry]));

/** @type {Map<string, object>} */
export const DOMAIN_BY_ID = new Map(PATTERN_DOMAINS.map((domain) => [domain.id, domain]));

/** Every rule across every domain, keyed by rule id. */
export const RULE_BY_ID = new Map(
  PATTERN_DOMAINS.flatMap((domain) => domain.rules.map((rule) => [rule.id, { ...rule, domain: domain.id }]))
);

function p(id, name, domain, role, problem, signals, benefit, cost, justifiedAt, extra = {}) {
  return Object.freeze({
    id,
    name,
    domain,
    role,
    problem,
    signals: Object.freeze(signals),
    benefit: Object.freeze(benefit),
    cost: Object.freeze(cost),
    justifiedAt,
    requires: Object.freeze(extra.requires ?? []),
    conflictsWith: Object.freeze(extra.conflictsWith ?? []),
    alternatives: Object.freeze(extra.alternatives ?? []),
    flowsTo: Object.freeze(extra.flowsTo ?? [])
  });
}
