flowchart TB
  subgraph n_src_static_analysis_resolve["src-static-analysis-resolve"]
    n_RESOLVE_EXTENSIONS["RESOLVE_EXTENSIONS"]
    n_TS_CONFIG_FILES["TS_CONFIG_FILES"]
    n_BUNDLER_CONFIG_FILES["BUNDLER_CONFIG_FILES"]
  end
